language: php

dist: trusty

git:
    submodules: true

php:
  - '7.1'
  - '7.2'

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - composer require phpunit/phpunit:^6.0 satooshi/php-coveralls:dev-master
    - composer install --dev
    - mkdir ./test/logs

install:
  - composer install

script: ./vendor/phpunit/phpunit/phpunit --coverage-clover ./test/logs/clover.xml --configuration test/phpunit.xml

after_script:
  - php /vendor/satooshi/php-coveralls/bin/php-coveralls -v