language: php

dist: precise


php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm


before_install:
  - git submodule update --init --recursive

install:
  - composer install

script: phpunit --configuration test/phpunit.xml