language: php

dist: precise


php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm


install:
  - composer install

before_script:
  - wget https://phar.phpunit.de/phpunit.phar test

script: php test/phpunit.phar --configuration phpunit_mysql.xml